### ISSUE TITLE
PreviewMenu is not displaying in Safari

### ISSUE THREAD

**Issue by JonQuayle** [prismicio/prismic-next#21]
### Versions

- `@prismicio/next`: v0.1.2
- `next`: v12.1.0

### What is expected?

The blue PreviewMenu to display in the bottom left corner of the screen when viewing the preview of a document.

### What is actually happening?

PreviewMenu is not displaying on Safari version 15.4 where as it is displaying fine in Google Chrome and Firefox.

**Comment by angeloashmore** [comment]
Hi @JonQuayle,

This could be a result of Safari's strict cross-site cookie policy. While this policy is great for privacy, it breaks functionality where cross-site checking is needed, such as checking your Prismic status.

Could you try this out? https://community.prismic.io/t/troubleshooting-previews/5449#are-your-previews-not-working-in-safari-12

If you would like to keep "Prevent cross-site tracking" checked, it likely means you will not be able to use the Prismic toolbar in Safari. In these cases, we recommend using Chrome or a different browser that does not block this functionality by default.

I'm going to close this issue since that should solve it, but please reply here if you have any questions or comments. Thanks!
