### ISSUE TITLE
Updating to 0.1.2 adds the next/image chunk to my final bundle even if I don't use next/image

### ISSUE THREAD

**Issue by gutierrez-cesar** [prismicio/prismic-next#35]
### Versions
- `@prismicio/next`: 0.1.3
- `next`: 12.2.5
- node: 14.19.3

### Steps to reproduce
- Run `next/bundle-analyzer` on v0.1.2 and the `next/image` chunk is not present . 
- Upgrade to v0.1.3 without changing anything else and the `next/image` chunk is now there.
<img width="362" alt="image" src="https://user-images.githubusercontent.com/91154920/186544106-327d4d60-b6e4-41e3-8220-c0bab7d00acb.png">

### What is expected?
I would expect the `next/image` chunk to not be included in my project if I don't use the next Image component

**Comment by angeloashmore** [comment]
Thanks for the bug report, @gutierrez-cesar. The `<PrismicNextImage>` component was introduced in `v0.1.3` which is why you are only seeing the added code after upgrading.

If you aren't using the component, it is supposed to be tree-shaken and excluded from the bundle. It likely is not being removed currently because the package does not mark itself as "side-effect free."

I will investigate. 🙂

**Comment by angeloashmore** [comment]
Hi @gutierrez-cesar, this should be fixed in `v0.1.4`.

The package needed to be built in a different way where it no longer bundles everything into one file. Since this package will always be used in Next.js, we can rely on Next.js to bundle. This lets Next.js's  bundler omit code that is not used.

You can update to the latest version with the following command:

```sh
npm install @prismicio/next@latest
```

If you are still noticing `next/image` in your builds, you may need to delete Next.js's build cache. You can clear it by deleting the `.next` directory that is created after building.

Thanks for the report! 🙂
