### ISSUE TITLE
the alt prop of the PrismicNextImage component has a type issue

### ISSUE THREAD

**Issue by aynzad** [prismicio/prismic-next#44]
### Versions

- `@prismicio/next`: 0.1.3
- `next`: 12.3.0
- `node`: 14.19.3

### Reproduction

use prismicio-community/nextjs-starter-prismic-blog as sample project

<details>
<summary>Additional Details</summary>
<br>package.json:<br>

```
{
  "name": "test-next-theme",
  "version": "1.0.0",
  "license": "Apache-2.0",
  "scripts": {
    "dev": "concurrently \"npm:next:dev\" \"npm:slicemachine\" --names \"next,slicemachine\" --prefix-colors blue,magenta",
    "next:dev": "next",
    "build": "next build",
    "start": "next start",
    "test": "jest --watch",
    "test:ci": "jest --ci",
    "test:coverage": "jest --coverage",
    "lint": "next lint",
    "slicemachine": "start-slicemachine",
    "format": "prettier --write .",
    "gen": "prismic-ts-codegen",
    "prepare": "husky install"
  },
  "prettier": {
    "semi": false,
    "singleQuote": true,
    "printWidth": 80,
    "trailingComma": "none",
    "arrowParens": "avoid",
    "endOfLine": "auto"
  },
  "dependencies": {
    "@prismicio/client": "^6.7.1",
    "@prismicio/helpers": "^2.3.4",
    "@prismicio/next": "^0.1.3",
    "@prismicio/react": "^2.5.0",
    "@prismicio/slice-simulator-react": "^0.2.2",
    "clsx": "^1.2.1",
    "next": "12.3.0",
    "react": "18.2.0",
    "react-dom": "18.2.0"
  },
  "devDependencies": {
    "@commitlint/cli": "^8.0.0",
    "@commitlint/config-conventional": "^8.0.0",
    "@commitlint/prompt-cli": "^8.0.0",
    "@prismicio/types": "^0.2.3",
    "@tailwindcss/aspect-ratio": "^0.4.0",
    "@tailwindcss/typography": "^0.5.7",
    "@testing-library/jest-dom": "5.16.4",
    "@testing-library/react": "13.2.0",
    "@testing-library/user-event": "14.2.0",
    "@types/react": "18.0.20",
    "@typescript-eslint/eslint-plugin": "^5.21.0",
    "autoprefixer": "^10.4.11",
    "concurrently": "^7.3.0",
    "eslint": "8.22.0",
    "eslint-config-next": "12.2.5",
    "eslint-config-prettier": "^8.1.0",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-prettier": "^3.1.3",
    "jest": "28.1.0",
    "jest-environment-jsdom": "28.1.0",
    "husky": "^8.0.0",
    "postcss": "^8.4.16",
    "prettier": "^2.7.1",
    "prettier-plugin-tailwindcss": "^0.1.13",
    "prismic-ts-codegen": "^0.1.2",
    "slice-machine-ui": "^0.4.2",
    "tailwindcss": "^3.1.8"
  }
}
```
</details>

### Steps to reproduce
```npx degit prismicio-community/nextjs-starter-prismic-blog your-project-name
cd your-project-name
npm i
npx @slicemachine/init
```
- Configure TS  https://nextjs.org/docs/basic-features/typescript#existing-projects
- Open `slices/Image/index.tsx` file
- Try to add `alt="something"` to the `PrismicNextImage` component

### What is expected?
- Add a non-empty string as the image alt prop

### What is actually happening?
- the PrismicNextImage only accepts the empty string (`''`) as the image alt prop

<img width="828" alt="Screen Shot 2022-09-23 at 18 31 17" src="https://user-images.githubusercontent.com/3133497/191997891-60bfb8c7-9f25-466e-8c38-ff8f530aa2d0.png">

### Possible fix
the `alt` and `fallbackAlt` of PrismicNextImageProps should be `string` type
<img width="904" alt="Screen Shot 2022-09-23 at 18 38 51" src="https://user-images.githubusercontent.com/3133497/191999273-7bedf947-0739-4fd0-8dbe-7dab4f86b377.png">

**Comment by angeloashmore** [comment]
Hi @aynzad, sorry for the late reply. I was on vacation the past couple of weeks, but I'm back now and reviewing issues.

This behavior is actually expected; the `alt` prop only supports an empty string value (i.e. `alt=""`, not `alt="some string"`). Alt text should be managed in Prismic *unless you are marking the image as decorative via `alt=""`. `<PrismicNextImage>` will automatically use the alt text from Prismic as the `alt` attribute's value.

For more details on this decision, see this message: [**`alt` must be an empty string**](https://github.com/prismicio/prismic-next/blob/main/messages/alt-must-be-an-empty-string.md)

I'm going to close this issue as the types reflect the intentional design, but please feel free to provide any feedback or suggestions if you have any here. Thanks! 🙂

**Comment by paulcoyle** [comment]
Hi @angeloashmore I am hitting this issue now and, while I guess I understand this decision, it seems a bit restrictive and not what one would expect.  I can see scenarios where you may want to alter the `alt` text depending on the context.  Additionally, users that manage images may not always provide an `alt` text.  For that scenario, there is the `fallbackAlt` prop but it also suffers from this type of `"" | undefined`.

```ts
export type PrismicNextImageProps = Omit<ImageProps, "src" | "alt"> & {
    // ...
    /**
     * Declare an image as decorative by providing `alt=""`.
     *
     * See:
     * https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/alt#decorative_images
     */
    alt?: "";
    /**
     * Declare an image as decorative only if the Image field does not have
     * alternative text by providing `fallbackAlt=""`.
     *
     * See:
     * https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/alt#decorative_images
     */
    fallbackAlt?: "";
    // ...
};
```

Basically, users cannot override the `alt` for an image and, if `alt` is not supplied on an image in prismic, there is no way to supply a fallback other than indicating that it is decorative.

A design I think may improve on this would allow the user to override the `alt` on the Prismic image via the `alt` prop whether it exists or not.  You could keep the `fallbackAlt` to be used when the Prismic image does not have `alt` text defined.  Lastly, if the user wants the use of this image instance to be decorative, a prop like `isDecorative` or `decorative` would then force the `img`'s `alt` to `""` plus it would be a bit more semantic.  You could output a warning if one of `alt` or `fallbackAlt` were provided when the `decorative` is `true`.

e.g. When the prismic image (`image`) **has** `alt` defined:

```tsx
<PrismicNextImage field={image} /> 
{/* <img alt="from prismic image" ... /> */}

<PrismicNextImage field={image} alt="overridden" />
 {/* <img alt="overridden" ... /> */}

<PrismicNextImage field={image} fallbackAlt="fallback" /> 
{/* <img alt="from prismic image" ... /> */}

<PrismicNextImage field={image} decorative /> 
{/* <img alt="" ... /> */}

<PrismicNextImage field={image} decorative alt="superseded by decorative" />
{/* <img alt="" ... /> */}
{/* Emits warning about `decorative` superseding props `alt` and `fallbackAlt` */}

<PrismicNextImage field={image} decorative fallbackAlt="superseded by decorative" /> 
{/* <img alt="" ... /> */}
{/* Emits warning about `decorative` superseding props `alt` and `fallbackAlt` */}
```

e..g. When the prismic image (`image`) **does not have** `alt` defined:

```tsx
<PrismicNextImage field={image} /> 
{/* <img ... /> */}
{/* Emits warning similar to the existing one, also points user to `decorative` prop. */}

<PrismicNextImage field={image} alt="overridden" />
 {/* <img alt="overridden" ... /> */}

<PrismicNextImage field={image} fallbackAlt="fallback" /> 
{/* <img alt="fallback" ... /> */}

<PrismicNextImage field={image} decorative /> 
{/* <img alt="" ... /> */}

<PrismicNextImage field={image} decorative alt="superseded by decorative" />
{/* <img alt="" ... /> */}
{/* Emits warning about `decorative` superseding props `alt` and `fallbackAlt` */}

<PrismicNextImage field={image} decorative fallbackAlt="superseded by decorative" /> 
{/* <img alt="" ... /> */}
{/* Emits warning about `decorative` superseding props `alt` and `fallbackAlt` */}
```

**Comment by angeloashmore** [comment]
Hey @paulcoyle, thank you for such a detailed proposal. 🙂

The decision to only support `alt=""` and `fallbackAlt=""` is to push content writers and developers to write alt text in Prismic. The reasoning is that "correct" alt text can't be written without seeing the image. A developer theoretically would not be able to write alt text for arbitrary images using an `alt` prop.

A developer can, however, know when a certain image is only for decorative purposes, since the developer knows the visual design.

We decided against using a prop like `decorative` over `alt=""` because `decorative` is, in our opinion, an unnecessary abstraction. `alt=""` is well known to mean "mark as decorative", thus we didn't find it necessary to replace that convention.

It also introduces an invalid state where you could set `decorative={true} alt="example alt"`—which one takes priority?

I'm happy to hear back from you if you have any additional thoughts! 🙂
