### ISSUE TITLE
exitPreview() is not working

### ISSUE THREAD

**Issue by kb1995** [prismicio/prismic-next#45]
Packages version:

```
"@prismicio/client": "^6.7.1",
    "@prismicio/helpers": "^2.3.5",
    "@prismicio/next": "^0.1.5",
    "@prismicio/react": "^2.4.4",
```

`api/exit-preview.js` is as follows:

```
import { exitPreview } from "@prismicio/next"

export default async function exit(req, res) {
  await exitPreview({ res, req })
}
```

Steps to reproduce:

- Preview a page
- Open preview - preview works
- click on exit preview in the toolbar
- toolbar is gone but the preview data is still there!

**Comment by angeloashmore** [comment]
Hey @kb1995, I was away on vacation but I'm back now. 🙂

There was a bug in `@prismicio/next` that caused this exact issue when deploying to CDNs that aggressively cache API route responses, including as Vercel. This is fixed as of `v0.1.4` where `exitPreview()` now returns a 205 status code. For more details on the issue and the fix, see #32.

I see you're using at least `v0.1.5`, which already includes the fix, so you may have a cached response stored in your browser. Could you clear your browser cache (specifically for the `/api/exit-preview` route) and try again? **You should see a 205 status code on the `/api/exit-preview` route, not a 200.**

Please let me know if this fixes the issue. Thanks!

**Comment by angeloashmore** [comment]
I'm going to close this issue as it has become stale, but feel free to reply here. We can continue the discussion and re-open if necessary. Thanks! 🙂

**Comment by grahamd711** [comment]
hi @angeloashmore we get a 500 error when calling exitPreview using draftMode().disable(). 

Steps to recreate:

1. Preview an unpublished document
2. Close the Prismic toolbar
3. Next.js App shows 500 error

Is this expected behavior? it seems it is based on the code.

`if (config?.res) {
		// Assume Preview Mode is being used.

		config.res.clearPreviewData();

		// `Cache-Control` header is used to prevent CDN-level caching.
		config.res.setHeader("Cache-Control", "no-store");

		config.res.json({ success: true });

		return;
	} else {
		// Assume Draft Mode is being used.

		draftMode().disable();

		// `Cache-Control` header is used to prevent CDN-level caching.
		return new Response(JSON.stringify({ success: true }), {
			headers: {
				"Cache-Control": "no-store",
			},
		});
	}`

![Screenshot 2024-09-23 at 10 32 01 AM](https://github.com/user-attachments/assets/1b53ac5f-018c-4253-b8cd-f879b121a77b)

This only happens on unpublished drafts, but is there any way to improve this experience? maybe redirect content editor to homepage?
