### ISSUE TITLE
File `libraries-state.json` not found inside '.slicemachine' folder

### ISSUE THREAD

**Issue by nirajniroula** [prismicio/prismic-next#56]
### Versions

- `@prismicio/next`:  "^1.0.2"
- `next`: "13.1.1"
- node:  v18.12.1

### Reproduction
I followed [the prismic documentation](https://prismic.io/docs/setup-nextjs) to install and configure Prismic in a Next.js project. Both nextjs as well as slicemachine ran without issues up to this point. But when I create a slice in slicemachine and try to simulate the newly created slice, simulator tab (in browser) shows;

 ![image](https://user-images.githubusercontent.com/11739133/209612319-996c7a3a-5001-48ec-9b3b-2c448111dacc.png)

And the tab running nextjs shows the following error;

![image](https://user-images.githubusercontent.com/11739133/209611837-c311be37-8388-4a13-93cb-c566ac341479.png)

If I add the file `libraries-state.json`, with an empty object, inside the `.slicemachine` folder manually there will be no such errors. But again, the file remains empty even while creating and updating slices in slicemachine, which I believe is not the expected behavior.

**Comment by lihbr** [comment]
Hey there, really sorry for the lack of support during the last two weeks!

Actually, importing the `libraries-state.json` file and feeding it to the Slice Simulator component is no longer needed. The fact that you encountered it was due to a miscommunication on our end on updating our documentation.

The documentation is now updated and shouldn't mislead users like you again into this error: https://prismic.io/docs/setup-nextjs#create-slice-simulator-page

Thanks 🙌
