### ISSUE TITLE
NextRouter was not mounted error using PrismicPreview

### ISSUE THREAD

**Issue by MKlblangenois** [prismicio/prismic-next#57]
### Versions

- `@prismicio/next`: v1.0.2
- `next`: v13.1.1
- `node`: v16.14.0

### Reproduction

When I'm trying to add `<PrismicPreview />` inside my page, I got an error from NextJS

<details open>
<summary>Additional Details</summary>
<br>

Code used :

```tsx
// ./app/layout.tsx

"use client";

import { PrismicProvider } from "@prismicio/react";
import Link from "next/link";
interface RootLayoutProps {
	children: React.ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
	return (
		<html lang="fr">
			<head />

			<body>
				<PrismicProvider
					internalLinkComponent={(props) => <Link {...props} />}
				>
					<div>{children}</div>
				</PrismicProvider>
			</body>
		</html>
	);
};

export default RootLayout;
```

```tsx
// ./app/page.tsx

"use client";

import { PrismicPreview } from "@prismicio/next";
import { repositoryName } from "../library/prismic";

const Page = () => {
	return (
		<PrismicPreview repositoryName={repositoryName}>
			<h1>Hello world!</h1>
		</PrismicPreview>
	);
};

export default Page;
```
</details>

### What is actually happening?

Got an error from NextJS : `Error: NextRouter was not mounted. https://nextjs.org/docs/messages/next-router-not-mounted`.

### Possible way to fix that

When I look to vercel/next.js#43585, It seems like replace `next/router` by `next/navigation` (used inside `PrismicPreview.tsx` on line :58 for `useRouter`) can solve this issue.

**Comment by angeloashmore** [comment]
Hi @MKlblangenois, thanks for the report!

`@prismicio/next` does not support Next.js's beta `app` directory at this time. We are waiting for the feature to stabilize before supporting it since it will require significant changes to the package.

You can find more details about this decision here: https://github.com/prismicio/prismic-next/pull/48#issuecomment-1316270169

Since that comment was written, Next.js's `app` directory feature has improved, but we prefer waiting until it is more mature.

If you have any questions, please let us know! 🙂
